language: ruby
bundler_args: --without system_tests
rvm:
  - 2.0.0
script: "bundle exec rake test"
env:
  - "PUPPET_GEM_VERSION='< 4.0.0' FUTURE_PARSER='yes' STRICT_VARIABLES='no'"
  - "PUPPET_GEM_VERSION='< 4.0.0' FUTURE_PARSER='yes' STRICT_VARIABLES='yes'"
  - "PUPPET_GEM_VERSION='> 4.0.0'"
  - "PUPPET_GEM_VERSION='> 4.0.0' STRICT_VARIABLES='yes'"
